python -m torch.distributed.launch --nproc_per_node=2 --master_port 11697 chest_class_finetuning.py \
--batch_size 96 --input_size 224 \
    --epochs 100 --warmup_epochs 20 \
    --model beit_base_patch16_224 --nb_classes 1 \
    --imagenet_default_mean_and_std \
    --disable_rel_pos_bias --abs_pos_emb --use_cls \
    --layer_scale_init_value 0 \
    --mixup 0 --cutmix 0 \
    --lr 1e-5 --drop_path 0.1 --layer_decay 0.95 \
    --log_dir ./myoutput/ft_covidx/lr1e-5_new_log --smoothing 0 \
    --output_dir ./myoutput/ft_covidx/lr1e-5_new_output \
    --finetune ./CheXpert-v1.0-small/ckpts/checkpoint_best.pt \
    --dataset covidx